---
- name: Set PostgreSQL environment variables.
  template:
    src: postgres.sh.j2
    dest: /etc/profile.d/postgres.sh
    mode: 0644
  notify: restart postgresql

- name: Ensure PostgreSQL data directory exists.
  file:
    path: "{{ postgresql_pgdata }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    state: directory
    mode: 0700

- name: Check if PostgreSQL database is initialized.
  stat:
    path: "{{ postgresql_pgdata }}/PG_VERSION"
  register: pgdata_dir_version

- name: Extra initdb options
  debug:
    msg: "{{ postgresql_initdb_options|join(' ') }}"
    verbosity: 1

- name: Ensure PostgreSQL database is initialized.
  command: "pg_createcluster -d {{ postgresql_pgdata }} -p {{ postgresql_port }} \
            {{ postgresql_version }} {{ postgresql_cluster_name }} \
            {{ '-- '+postgresql_initdb_options|join(' ') if postgresql_initdb_options|length > 0 else '' }}"
  become: true
  become_user: "{{ postgresql_user }}"
  when:
    - postgresql_initialize_database
    - not pgdata_dir_version.stat.exists
    - ansible_os_family == 'Debian'

- name: Ensure PostgreSQL database is initialized.
  command: "{{ postgresql_bin_path }}/initdb -D {{ postgresql_pgdata }} {{ postgresql_initdb_options|join(' ') }}"
  become: true
  become_user: "{{ postgresql_user }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
  when:
    - postgresql_initialize_database
    - not pgdata_dir_version.stat.exists
    - ansible_os_family == 'RedHat'

- name: Configure non standard PostgreSQL port.
  lineinfile:
    dest: "{{ postgresql_config_path }}/postgresql.conf"
    regexp: "^#?port.+$"
    line: "port = {{ postgresql_port }}"
    state: present
  notify: restart postgresql
  when:
    - postgresql_initialize_database
    - postgresql_port != 5432
    - ansible_os_family == 'Debian' or (ansible_os_family == 'RedHat' and postgresql_version|float > 9.4)
