---
- name: Ensure PostgreSQL Python libraries are installed.
  apt:
    name: "{{ postgresql_python_library }}"
    state: present

- name: Ensure PostgreSQL packages are installed.
  apt:
    name: "{{ postgresql_packages }}"
    state: present
  register: package_installed

- name: Ensure all configured locales are present.
  locale_gen: "name={{ item }} state=present"
  with_items: "{{ postgresql_locales }}"
  register: locale_gen_result

- name: Ensure PostgreSQL is not running.
  service:
    name: postgresql
    state: stopped
  when:
    - postgresql_cluster_name != 'main'
    - package_installed.changed

- name: Ensure main cluster is not present (main is removed when PostgreSQL is just installed).
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ postgresql_default_main_cluster_path }}"
    - "{{ postgresql_default_main_cluster_configpath }}"
  when:
    - postgresql_cluster_name != 'main'
    - package_installed.changed
