---
# Variable configuration.
- name: Include OS-specific variables (Debian).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'Debian'

- name: Include OS-specific variables (RedHat).
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when:
  - ansible_os_family == 'RedHat'
  - ansible_distribution != 'Fedora'

- name: Include OS-specific variables (Fedora).
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_distribution == 'Fedora'

- name: Define postgresql_packages.
  set_fact:
    postgresql_packages: "{{ __postgresql_packages | list }}"
  when: postgresql_packages is not defined

- name: Define postgresql_version.
  set_fact:
    postgresql_version: "{{ __postgresql_version }}"
  when: postgresql_version is not defined

# Daemon name
- name: Define postgresql_daemon.
  set_fact:
    postgresql_daemon: "{{ __postgresql_daemon }}"
  when: postgresql_daemon is not defined

# PGDG vs Official
- name: Define installation source.
  set_fact:
    postgresql_pgdg: true
  when:
    - postgresql_version|float != __postgresql_version|float

- name: Assert version is supported by source.
  assert:
    that:
      postgresql_version == __postgresql_version
    fail_msg: "This version of PostgreSQL is not supported by OS repository"
  when:
    - postgresql_pgdg is defined
    - not postgresql_pgdg

# Data dir
- name: Define postgresql_data_dir.
  set_fact:
    postgresql_data_dir: "{{ __postgresql_data_dir }}"
  when: postgresql_data_dir is not defined

- name: Define PGDATA.
  set_fact:
    postgresql_pgdata: "{{ postgresql_data_dir }}/{{ postgresql_version }}/{{ postgresql_cluster_name }}"
  when: postgresql_pgdata is not defined

# Asserts on pgdata path
- name: Main cluster name can only be located in default path
  assert:
    that:
      - postgresql_cluster_name != 'main'
    fail_msg: Change postgresql_cluster_name or postgresql_data_dir
  when:
    - ansible_os_family == 'RedHat'
    - __postgresql_data_dir != postgresql_data_dir

- name: Define postgresql_bin_path.
  set_fact:
    postgresql_bin_path: "{{ __postgresql_bin_path }}"
  when: postgresql_bin_path is not defined

- name: Define postgresql_config_path for RedHat based system.
  set_fact:
    postgresql_config_path: "{{ postgresql_pgdata | default(__postgresql_config_path) }}"
  when:
    - postgresql_config_path is not defined
    - ansible_os_family == 'RedHat'

- name: Define postgresql_config_path for Debian based system.
  set_fact:
    postgresql_config_path: "{{ __postgresql_config_path }}"
  when:
    - postgresql_config_path is not defined
    - ansible_os_family == 'Debian'

- name: Define postgresql_initdb_options
  set_fact:
    postgresql_initdb_options: []
  when: postgresql_initdb_options is not defined

- name: Define postgresql_default_main_cluster_path for Debian based system
  set_fact:
    postgresql_default_main_cluster_path: "{{ __postgresql_default_main_cluster_path }}"
  when:
    - postgresql_default_main_cluster_path is not defined
    - ansible_os_family == 'Debian'

- name: Define postgresql_default_main_cluster_path for Debian based system
  set_fact:
    postgresql_default_main_cluster_configpath: "{{ __postgresql_default_main_cluster_configpath }}"
  when:
    - postgresql_default_main_cluster_configpath is not defined
    - ansible_os_family == 'Debian'

- name: Set postgresql slave wal dir
  set_fact:
    postgresql_slave_wal_dir: "{{ postgresql_data_dir }}/standby_wal/"
  when:
    - postgresql_slave_wal_dir is not defined

- name: Set postgresql trigger promote slave file
  set_fact:
    postgresql_slave_trigger_file: "{{ postgresql_config_path }}/pg_trigger"
  when:
    - postgresql_slave_host is defined
    - postgresql_slave_trigger_file is not defined

- name: Define if this instance is a slave instance
  set_fact:
    postgresql_is_slave: true
  when:
    - postgresql_slave_host is defined
    - (postgresql_slave_host == inventory_hostname or postgresql_slave_host == ansible_hostname )
